//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPartFlash.Gui.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WinPartFlash.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string SavePartition {
            get {
                return ResourceManager.GetString("SavePartition", resourceCulture);
            }
        }
        
        public static string WritePartition {
            get {
                return ResourceManager.GetString("WritePartition", resourceCulture);
            }
        }
        
        public static string LabelPartition {
            get {
                return ResourceManager.GetString("LabelPartition", resourceCulture);
            }
        }
        
        public static string ReloadPartition {
            get {
                return ResourceManager.GetString("ReloadPartition", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string WriteButton {
            get {
                return ResourceManager.GetString("WriteButton", resourceCulture);
            }
        }
        
        public static string ErrorNoPartition {
            get {
                return ResourceManager.GetString("ErrorNoPartition", resourceCulture);
            }
        }
        
        public static string LabelFileToSave {
            get {
                return ResourceManager.GetString("LabelFileToSave", resourceCulture);
            }
        }
        
        public static string LabelFileToFlash {
            get {
                return ResourceManager.GetString("LabelFileToFlash", resourceCulture);
            }
        }
        
        public static string LabelFormat {
            get {
                return ResourceManager.GetString("LabelFormat", resourceCulture);
            }
        }
        
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        public static string FileTypeNameDiskImages {
            get {
                return ResourceManager.GetString("FileTypeNameDiskImages", resourceCulture);
            }
        }
        
        public static string ConfirmFlashText {
            get {
                return ResourceManager.GetString("ConfirmFlashText", resourceCulture);
            }
        }

        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }

        public static string SectionSource {
            get {
                return ResourceManager.GetString("SectionSource", resourceCulture);
            }
        }

        public static string SectionDestination {
            get {
                return ResourceManager.GetString("SectionDestination", resourceCulture);
            }
        }

        public static string SectionFormat {
            get {
                return ResourceManager.GetString("SectionFormat", resourceCulture);
            }
        }

        public static string SectionProgress {
            get {
                return ResourceManager.GetString("SectionProgress", resourceCulture);
            }
        }

        public static string SectionTarget {
            get {
                return ResourceManager.GetString("SectionTarget", resourceCulture);
            }
        }

        public static string SectionStatus {
            get {
                return ResourceManager.GetString("SectionStatus", resourceCulture);
            }
        }

        public static string TabAdvanced {
            get {
                return ResourceManager.GetString("TabAdvanced", resourceCulture);
            }
        }

        public static string AdvancedComingSoon {
            get {
                return ResourceManager.GetString("AdvancedComingSoon", resourceCulture);
            }
        }

        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }

        public static string MenuSavePartition {
            get {
                return ResourceManager.GetString("MenuSavePartition", resourceCulture);
            }
        }

        public static string MenuFlashPartition {
            get {
                return ResourceManager.GetString("MenuFlashPartition", resourceCulture);
            }
        }

        public static string MenuAdvanced {
            get {
                return ResourceManager.GetString("MenuAdvanced", resourceCulture);
            }
        }

        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }

        public static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }

        public static string ConfirmDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmDialogTitle", resourceCulture);
            }
        }
    }
}
