//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPartFlash.Gui.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WinPartFlash.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string SavePartition {
            get {
                return ResourceManager.GetString("SavePartition", resourceCulture);
            }
        }
        
        public static string WritePartition {
            get {
                return ResourceManager.GetString("WritePartition", resourceCulture);
            }
        }
        
        public static string LabelPartition {
            get {
                return ResourceManager.GetString("LabelPartition", resourceCulture);
            }
        }
        
        public static string ReloadPartition {
            get {
                return ResourceManager.GetString("ReloadPartition", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string WriteButton {
            get {
                return ResourceManager.GetString("WriteButton", resourceCulture);
            }
        }
        
        public static string ErrorNoPartition {
            get {
                return ResourceManager.GetString("ErrorNoPartition", resourceCulture);
            }
        }
        
        public static string LabelFileToSave {
            get {
                return ResourceManager.GetString("LabelFileToSave", resourceCulture);
            }
        }
        
        public static string LabelFileToFlash {
            get {
                return ResourceManager.GetString("LabelFileToFlash", resourceCulture);
            }
        }
        
        public static string LabelFormat {
            get {
                return ResourceManager.GetString("LabelFormat", resourceCulture);
            }
        }
        
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        public static string FileTypeNameDiskImages {
            get {
                return ResourceManager.GetString("FileTypeNameDiskImages", resourceCulture);
            }
        }
        
        public static string ConfirmFlashText {
            get {
                return ResourceManager.GetString("ConfirmFlashText", resourceCulture);
            }
        }
    }
}
